server:
  port: 8080  # Порт, на котором будет работать приложение

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое обновление схемы БД
    show-sql: true  # Показывать SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springfox:
  documentation:
    swagger-ui:
      base-url: /swagger-ui/